### ISSUE TITLE
Out of date message 1.2.0

### ISSUE THREAD

**Issue by fredsanchez** [lywit/VU-More-Gore#2]
Love the mod.
Installed the 1.2.0 version and console says it is 1.1.3, out of date.

Removed old mod, installed new mod, started server multiple times, still getting out of date message.

Thank you
![More-Gore-Error](https://github.com/lywit/VU-More-Gore/assets/48363401/9da19e59-d1af-4f21-86ca-53380fb8ac81)

**Comment by lywit** [comment]
Thank you for bringing this up! I forgot to change a value somewhere.
It has been resolved in release 1.3.0
https://github.com/lywit/VU-More-Gore/releases/tag/Release-1.3.0
